Created Ansible test workflow
senior-design-21-22/ansible-collection-github pull request #14
Opened 2021-10-14 22:27 UTC by Khounborinn

The only added file would be the ansible-test.yml file that would run all of the ansible tests upon the branch that is getting pushed.

2021-10-15 14:34 UTC, jacobeicher requested changes

2021-10-15 14:34 UTC, jacobeicher commented on .github/workflows/ansible.yml
> +    branches: [ main ]
I would make these the development branch, we won't ever be committing to main

2021-10-15 18:54 UTC, klfgit commented on .github/workflows/ansible.yml
> +      - name: Perform unit testing with ansible-test
The order of testing should be: unit, sanity, integration.

2021-10-18 15:23 UTC, jacobeicher approved these changes

2021-10-18 15:25 UTC, bgolski approved these changes

2021-10-18 15:47 UTC, TylerZwolenik approved these changes

2021-10-18 15:55 UTC, merged