Collaborator list module multifunctional
senior-design-21-22/ansible-collection-github pull request #32
Opened 2021-10-27 22:24 UTC by jacobeicher

I have added a possible way to separate the multiple functions it will depend on how we want to do things I don't know if there is a right or wrong way it will depend on how we set things up and how we want to use this module in conjunction with other modules

2021-10-27 22:32 UTC, Khounborinn approved these changes

2021-10-27 22:41 UTC, TylerZwolenik requested changes
I am not sure if the "collaberator" is to avoid keyword conflict, but it is python practice to use "collaborator_", I am pretty sure.

2021-10-27 22:41 UTC, TylerZwolenik commented on plugins/modules/collaborator_information.py
> +def add_collaberators(repos, collaberators,):
```suggestion
def add_collaborators_(repos, collaborators_):
```
if this is to avoid conflicts with keywords, it is python practice to shove a underscore onto the back

2021-10-28 23:24 UTC, jacobeicher commented
Functionality should be completed, the playbook needs to be updated still

2021-10-29 00:31 UTC, bgolski commented on plugins/modules/collaborator_information.py
> +def del_collaberators(repos, collaberators):
All instances of collaberators should be "collaborators"

2021-10-29 00:32 UTC, merged