Pull request updates
senior-design-21-22/ansible-collection-github pull request #58
Opened 2021-11-04 19:15 UTC by jacobeicher

2021-11-05 00:01 UTC, bgolski requested changes

2021-11-05 00:01 UTC, bgolski commented on README.md
>        import_role:
We no longer use roles to run the module, so this should be changed to reflect that.

2021-11-05 01:20 UTC, TylerZwolenik approved these changes

2021-11-05 03:19 UTC, Khounborinn approved these changes

2021-11-12 16:14 UTC, bgolski approved these changes

2021-11-12 16:14 UTC, merged